[package]
name = "l-compilator"
version = "0.1.0"
authors = ["Loïc Escales <loic.escales@kakos.fr>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
lalrpop = "0.16.3"

[dependencies]
logos = "0.9.7"
lalrpop-util = "0.16.3"
structopt = "0.2.14"
exitfailure = "0.5.1"
