[package]
name = "l-compilateur"
version = "0.1.0"
authors = ["L0L022 <L0L022@openmailbox.org>"]
edition = "2018"
build = "build.rs"

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.16.3"

[dependencies]
logos = "0.9.7"
lalrpop-util = "0.16.3"
regex = "0.2.1"